name: test and benchmark

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Benchmark:
    name: Test and Benchmark
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v6

      - name: Set up PostgreSQL
        uses: ikalnytskyi/action-setup-postgres@v8
        id: postgres

      - name: Optimize PostgreSQL Configuration
        run: |
          psql ${{ env.PGURL }} -c "ALTER SYSTEM SET max_connections = '200';"
          psql ${{ env.PGURL }} -c "ALTER SYSTEM SET shared_buffers = '1792MB';"
          psql ${{ env.PGURL }} -c "ALTER SYSTEM SET effective_cache_size = '5376MB';"
          psql ${{ env.PGURL }} -c "ALTER SYSTEM SET maintenance_work_mem = '448MB';"
          psql ${{ env.PGURL }} -c "ALTER SYSTEM SET checkpoint_completion_target = '0.9';"
          psql ${{ env.PGURL }} -c "ALTER SYSTEM SET wal_buffers = '16MB';"
          psql ${{ env.PGURL }} -c "ALTER SYSTEM SET default_statistics_target = '100';"
          psql ${{ env.PGURL }} -c "ALTER SYSTEM SET random_page_cost = '1.1';"
          psql ${{ env.PGURL }} -c "ALTER SYSTEM SET effective_io_concurrency = '200';"
          psql ${{ env.PGURL }} -c "ALTER SYSTEM SET work_mem = '7939kB';"
          psql ${{ env.PGURL }} -c "ALTER SYSTEM SET huge_pages = 'off';"
          psql ${{ env.PGURL }} -c "ALTER SYSTEM SET jit = 'off';"
          psql ${{ env.PGURL }} -c "ALTER SYSTEM SET min_wal_size = '1GB';"
          psql ${{ env.PGURL }} -c "ALTER SYSTEM SET max_wal_size = '4GB';"
          psql ${{ env.PGURL }} -c "ALTER SYSTEM SET wal_compression = 'lz4';"
          psql ${{ env.PGURL }} -c "ALTER SYSTEM SET io_method = 'io_uring';"
          
          sudo systemctl restart postgresql
        env:
          PGURL: ${{ steps.postgres.outputs.connection-uri }}

      - run: psql ${{ steps.postgres.outputs.connection-uri }} -f ./pgmq.sql

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: Run tests and benchmarks
        uses: sanbei101/go-bench-pprof-action@v1
        with:
          top: 10
          mem: true
        env:
          DATABASE_URL: ${{ steps.postgres.outputs.connection-uri }}
          GOEXPERIMENT: jsonv2